### ISSUE TITLE
Internet Explorer

### ISSUE THREAD

**Issue by michaelpwilson** [ng-lightning/ng-lightning#121]
Hey there,

Really nice work going on here!

I had a question about the support for Internet Explorer. I see only Edge is supported, but is there any reason to why IE 10 or 11 isn't supported?

Is there any potential for a possible fix?

**Comment by bekos** [comment]
Hi @michaelpwilson and thanks for your kind words :-)

IE11 is something we _do_ want to support and I hope to do soon. The main reason for not doing this yet, is that I don't have (easy) access to one! IE10 will not be "officially" supported since Lightning framework doesn't support it either and you will have issues anyway, but I don't think it will need any extra care from us if IE11 is working.

I'm leaving this open until IE11 is fully supported. If you think you can help, any PR will be highly appreciated :-)

**Comment by michaelpwilson** [comment]
Thanks for the speedy reply @bekos :)

Ok cool, I'll try and take a look tonight and see what I can do :+1:

**Comment by dballance** [comment]
#150 - Adding the polyfills should resolve. I see good support for all components with a quick look over.

**Comment by dballance** [comment]
There is probably room for some discussion of alternatives, but I wanted to make sure something worked quick and dirty before looking at what can be done to possibly resolve without polyfills.

**Comment by istiti** [comment]
Thanks to fix it for ie11, I think ie10 have to be supported too, but I have not one to check the official LDS under ie10

otherwise I really don't understand how it's possible that css going buggy under ie11, the official webpage LDS component it works great, you changed the LDS css plugin or why this react like this, I thinked it will be the same result as the official css... very very strange. 

great repo, tanks hope it will become better in a few  weeks ;-)

**Comment by dballance** [comment]
#163 Should close. 

@istiti I doubt IE10 would be supported. Both Angular2 and SLDS do not support IE10, only 11 + Edge. The bugs are in the JavaScript side of the lib, and purely because Microsoft refuses to implement standards :smile:. IE11 should work great if you add the required polyfills.

**Comment by bekos** [comment]
@dballance is right. IE 10 is [not supported by LDS](https://www.lightningdesignsystem.com/faq/#what-browsers-are-supported), so we will not officially support it either.
