### ISSUE TITLE
scroller rows

### ISSUE THREAD

**Issue by rodrigoEclipsa** [ng-lightning/ng-lightning#314]
Is it possible to add support for vertical and horizontal scrolling for table rows?
From since already thank you very much.

**Comment by bekos** [comment]
@rodrigoEclipsa Thx for using ng-lightning, but I don't think we are going to support this feature, since our CSS framework, LDS doesn't support such functionality. Perhaps, a general third party plugin could work well, since our `datatable` is actually an HTML `<table>`. Closing as this is not actionable atm.
