### ISSUE TITLE
ng 4.0

### ISSUE THREAD

**Issue by ronnyek** [ng-lightning/ng-lightning#316]
Looking to see if angular4 is on the radar at this point. <template tag was deprecated for preferred ng-template.

**Comment by bekos** [comment]
hi @ronnyek. Since v4 is backwards compatible, ng-lightning should have no problem running inside Angular v4 applications. Actually all the plunker examples are executed with the latest Angular, ie v4.0.1

We will definitely upgrade to Angular 4, but not very soon, as we prefer to have a few warnings in v4 applications, instead of breaking the existing v2 applications. Closing as this is not actionable atm, and already in our radar 👍
