### ISSUE TITLE
support angular 6 and rxjs 6

### ISSUE THREAD

**Issue by rodrigoEclipsa** [ng-lightning/ng-lightning#378]
is the support for angular 6 and rxjs 6 planned?

**Comment by adamkundrat** [comment]
based on amount updates there are on this project I don't much is going to happen:(

**Comment by herrevilkitten** [comment]
As a temporary measure, it looks like you can use the `rxjs-compat` module.  I installed it and it started building again.

https://www.npmjs.com/package/rxjs-compat

**Comment by AnBauer** [comment]
As mentioned in another issue, I have published my version under `ngx-lightning` with Angular 6+ support - no rxjs-compat needed.

**Comment by ruben-osre** [comment]
@AnBauer Your lib is awesome, thanks!

**Comment by bekos** [comment]
There is a new release v4.0.0 🎉 with support for latest Angular and LDS, with many new components, re-write for many of the existing ones and many improvements and bug fixes.

I know there has been a lot of time with limited to no updates, but this was due to our limited time/resources and the build/release/demo infrastructure that made releases more difficult to achieve. I know this is sad, because ng-lightning is a project we really care about and a project I know that a lot of people use.

Hopefully, this will change now, as we plan more frequent updates and new components on every nw release, as we try to catch up with all the new components that LDS now offers!

@AnBauer I know we weren't very responsive and your fork was really helpful for some people from what I can see. I suppose/hope that you are still use ng-lightning and propose to focus your efforts on helping this library thrive :)

**Comment by Ralms** [comment]
@bekos thank you very much for your work.

I'm happy to be able to use this project again as I'm in Angular 7 :)
