### ISSUE TITLE
Npm install fails on preinstall script

### ISSUE THREAD

**Issue by niralpokal** [ng-lightning/ng-lightning#424]
I appreciate the amount of time that was spent updating and maintaining this project and am excited on the latest slds updates. I have a project that is using angular 7 with rxjs 6 and I saw you updated the master repo with what looks like fixes to rxjs 6 issues. When I went to install it with npm I got an error to tell me to use yarn. I understand that yarn is used to build the project but I was wondering if there was a workaround on using npm to install the package or maybe it was an oversight? 

<img width="584" alt="Screen Shot 2019-03-22 at 11 20 19 AM" src="https://user-images.githubusercontent.com/14898222/54844648-9c243480-4c94-11e9-86e9-59a1d90b296f.png">

**Comment by bekos** [comment]
@niralpokal This is used for developers of ng-lighntning. We have taken a decision to use Yarn inside this project, and in order to prevent people from installing with npm, submitting package-lock etc only to find out later that we don't use npm, we added this script.

Nevertheless, if you want to override it locally on your machine, you can just delete the `preinstall` script from `package.json` and then run `npm install`. I hope this solves your issue :)

btw the new release is out in the public 🎉
