### ISSUE TITLE
ngl-icon: please, don't use class 'slds-icon-text-default'  by default

### ISSUE THREAD

**Issue by sadesyllas** [ng-lightning/ng-lightning#58]
In some cases, as is the case of the pill component, class 'slds-icon-text-default' does not allow correct rendering of icons.

**Comment by bekos** [comment]
@sadesyllas Can you see if #61 works for you by providing `<ng-icon type="" ...></ngl-icon>`?

**Comment by sadesyllas** [comment]
@bekos, I reproduced the first example at https://www.lightningdesignsystem.com/components/icons/ as such:

```html
<ngl-icon class="slds-icon_container slds-icon_container--circle slds-icon-action-description" icon="description" type="" size="small"></ngl-icon>
```

It seems that non-```slds-icon-text-...``` icons need a specific container to display properly (as per https://www.lightningdesignsystem.com/components/icons/). Other than that, explicitly unsetting ```type``` works.

Is this the common case, though?

**Comment by bekos** [comment]
Indeed, we don't handle containers (backgrounds) for `ngl-icon`s yet. This issue was just to provide a way for you to unset the `slds-icon-text-default`, which btw is the common case for non back-grounded icons. If this is OK, we can merge this PR, and open new issues if you see anything else missing or needs improving :-)

**Comment by vellerefond** [comment]
Agreed. Let's handle more complex scenarios later.

**Comment by sadesyllas** [comment]
Agreed. Let's handle more complex scenarios later.
